// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

public final class Ast {
  private Ast() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_LibraryDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_LibraryDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_FunctionDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_FunctionDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_LitByte_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_LitByte_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_LitShort_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_LitShort_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_LitInt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_LitInt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_LitLong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_LitLong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_Get_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_Get_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_Apply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_Apply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_Expr_LoadArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_Expr_LoadArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_TypeExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_TypeExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_TypeExpr_Literal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_TypeExpr_Literal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peacod_ast_TypeExpr_Variable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peacod_ast_TypeExpr_Variable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ast/src/main/ast.proto\022\npeacod_ast\"V\n\n" +
      "LibraryDef\022\017\n\007version\030\001 \001(\r\022\014\n\004name\030\002 \001(" +
      "\t\022)\n\010function\030\003 \003(\0132\027.peacod_ast.Functio" +
      "nDef\"x\n\013FunctionDef\022\014\n\004name\030\001 \001(\t\022\027\n\017num" +
      "_type_params\030\002 \001(\r\022\"\n\004type\030\003 \001(\0132\024.peaco" +
      "d_ast.TypeExpr\022\036\n\004body\030\004 \001(\0132\020.peacod_as" +
      "t.Expr\"\373\005\n\004Expr\022)\n\006simple\030\001 \001(\0162\027.peacod" +
      "_ast.Expr.SimpleH\000\022,\n\010lit_byte\030\002 \001(\0132\030.p" +
      "eacod_ast.Expr.LitByteH\000\022.\n\tlit_short\030\003 " +
      "\001(\0132\031.peacod_ast.Expr.LitShortH\000\022*\n\007lit_" +
      "int\030\004 \001(\0132\027.peacod_ast.Expr.LitIntH\000\022,\n\010" +
      "lit_long\030\005 \001(\0132\030.peacod_ast.Expr.LitLong" +
      "H\000\022#\n\003get\030\006 \001(\0132\024.peacod_ast.Expr.GetH\000\022" +
      "\'\n\005apply\030\007 \001(\0132\026.peacod_ast.Expr.ApplyH\000" +
      "\022,\n\010load_arg\030\r \001(\0132\030.peacod_ast.Expr.Loa" +
      "dArgH\000\032\030\n\007LitByte\022\r\n\005value\030\001 \001(\005\032\031\n\010LitS" +
      "hort\022\r\n\005value\030\001 \001(\005\032\027\n\006LitInt\022\r\n\005value\030\001" +
      " \001(\005\032\030\n\007LitLong\022\r\n\005value\030\001 \001(\003\032u\n\003Get\022\017\n" +
      "\007library\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\"\n\004type\030\003 \001" +
      "(\0132\024.peacod_ast.TypeExpr\022+\n\rtype_argumen" +
      "t\030\005 \003(\0132\024.peacod_ast.TypeExpr\032O\n\005Apply\022\"" +
      "\n\010function\030\001 \001(\0132\020.peacod_ast.Expr\022\"\n\010ar" +
      "gument\030\002 \003(\0132\020.peacod_ast.Expr\032<\n\007LoadAr" +
      "g\022\"\n\004type\030\001 \001(\0132\024.peacod_ast.TypeExpr\022\r\n" +
      "\005index\030\002 \001(\r\"\035\n\006Simple\022\t\n\005FALSE\020\000\022\010\n\004TRU" +
      "E\020\001B\007\n\005value\"\344\001\n\010TypeExpr\022/\n\007literal\030\001 \001" +
      "(\0132\034.peacod_ast.TypeExpr.LiteralH\000\0221\n\010va" +
      "riable\030\002 \001(\0132\035.peacod_ast.TypeExpr.Varia" +
      "bleH\000\032P\n\007Literal\022\017\n\007library\030\001 \001(\t\022\014\n\004nam" +
      "e\030\002 \001(\t\022&\n\010argument\030\003 \003(\0132\024.peacod_ast.T" +
      "ypeExpr\032\031\n\010Variable\022\r\n\005index\030\001 \001(\rB\007\n\005va" +
      "lueB!\n\035com.sstewartgallus.peacod.astP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_peacod_ast_LibraryDef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_peacod_ast_LibraryDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_LibraryDef_descriptor,
        new java.lang.String[] { "Version", "Name", "Function", });
    internal_static_peacod_ast_FunctionDef_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_peacod_ast_FunctionDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_FunctionDef_descriptor,
        new java.lang.String[] { "Name", "NumTypeParams", "Type", "Body", });
    internal_static_peacod_ast_Expr_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_peacod_ast_Expr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_descriptor,
        new java.lang.String[] { "Simple", "LitByte", "LitShort", "LitInt", "LitLong", "Get", "Apply", "LoadArg", "Value", });
    internal_static_peacod_ast_Expr_LitByte_descriptor =
      internal_static_peacod_ast_Expr_descriptor.getNestedTypes().get(0);
    internal_static_peacod_ast_Expr_LitByte_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_LitByte_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_peacod_ast_Expr_LitShort_descriptor =
      internal_static_peacod_ast_Expr_descriptor.getNestedTypes().get(1);
    internal_static_peacod_ast_Expr_LitShort_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_LitShort_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_peacod_ast_Expr_LitInt_descriptor =
      internal_static_peacod_ast_Expr_descriptor.getNestedTypes().get(2);
    internal_static_peacod_ast_Expr_LitInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_LitInt_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_peacod_ast_Expr_LitLong_descriptor =
      internal_static_peacod_ast_Expr_descriptor.getNestedTypes().get(3);
    internal_static_peacod_ast_Expr_LitLong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_LitLong_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_peacod_ast_Expr_Get_descriptor =
      internal_static_peacod_ast_Expr_descriptor.getNestedTypes().get(4);
    internal_static_peacod_ast_Expr_Get_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_Get_descriptor,
        new java.lang.String[] { "Library", "Name", "Type", "TypeArgument", });
    internal_static_peacod_ast_Expr_Apply_descriptor =
      internal_static_peacod_ast_Expr_descriptor.getNestedTypes().get(5);
    internal_static_peacod_ast_Expr_Apply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_Apply_descriptor,
        new java.lang.String[] { "Function", "Argument", });
    internal_static_peacod_ast_Expr_LoadArg_descriptor =
      internal_static_peacod_ast_Expr_descriptor.getNestedTypes().get(6);
    internal_static_peacod_ast_Expr_LoadArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_Expr_LoadArg_descriptor,
        new java.lang.String[] { "Type", "Index", });
    internal_static_peacod_ast_TypeExpr_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_peacod_ast_TypeExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_TypeExpr_descriptor,
        new java.lang.String[] { "Literal", "Variable", "Value", });
    internal_static_peacod_ast_TypeExpr_Literal_descriptor =
      internal_static_peacod_ast_TypeExpr_descriptor.getNestedTypes().get(0);
    internal_static_peacod_ast_TypeExpr_Literal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_TypeExpr_Literal_descriptor,
        new java.lang.String[] { "Library", "Name", "Argument", });
    internal_static_peacod_ast_TypeExpr_Variable_descriptor =
      internal_static_peacod_ast_TypeExpr_descriptor.getNestedTypes().get(1);
    internal_static_peacod_ast_TypeExpr_Variable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peacod_ast_TypeExpr_Variable_descriptor,
        new java.lang.String[] { "Index", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
