// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

public interface ExprOrBuilder extends
        // @@protoc_insertion_point(interface_extends:peacod_ast.Expr)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.peacod_ast.Expr.Variable variable = 1;</code>
     *
     * @return Whether the variable field is set.
     */
    boolean hasVariable();

    /**
     * <code>.peacod_ast.Expr.Variable variable = 1;</code>
     *
     * @return The variable.
     */
    com.sstewartgallus.peacod.ast.Expr.Variable getVariable();

    /**
     * <code>.peacod_ast.Expr.Variable variable = 1;</code>
     */
    com.sstewartgallus.peacod.ast.Expr.VariableOrBuilder getVariableOrBuilder();

    /**
     * <code>.peacod_ast.Expr.Constant constant = 2;</code>
     *
     * @return Whether the constant field is set.
     */
    boolean hasConstant();

    /**
     * <code>.peacod_ast.Expr.Constant constant = 2;</code>
     *
     * @return The constant.
     */
    com.sstewartgallus.peacod.ast.Expr.Constant getConstant();

    /**
     * <code>.peacod_ast.Expr.Constant constant = 2;</code>
     */
    com.sstewartgallus.peacod.ast.Expr.ConstantOrBuilder getConstantOrBuilder();

    /**
     * <code>.peacod_ast.Expr.Call call = 3;</code>
     *
     * @return Whether the call field is set.
     */
    boolean hasCall();

    /**
     * <code>.peacod_ast.Expr.Call call = 3;</code>
     *
     * @return The call.
     */
    com.sstewartgallus.peacod.ast.Expr.Call getCall();

    /**
     * <code>.peacod_ast.Expr.Call call = 3;</code>
     */
    com.sstewartgallus.peacod.ast.Expr.CallOrBuilder getCallOrBuilder();

    public com.sstewartgallus.peacod.ast.Expr.ValueCase getValueCase();
}
