// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

public interface FunctionDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:peacod_ast.FunctionDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 num_type_params = 2;</code>
   */
  int getNumTypeParams();

  /**
   * <code>.peacod_ast.TypeExpr type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>.peacod_ast.TypeExpr type = 3;</code>
   */
  com.sstewartgallus.peacod.ast.TypeExpr getType();
  /**
   * <code>.peacod_ast.TypeExpr type = 3;</code>
   */
  com.sstewartgallus.peacod.ast.TypeExprOrBuilder getTypeOrBuilder();

  /**
   * <code>.peacod_ast.Expr body = 4;</code>
   */
  boolean hasBody();
  /**
   * <code>.peacod_ast.Expr body = 4;</code>
   */
  com.sstewartgallus.peacod.ast.Expr getBody();
  /**
   * <code>.peacod_ast.Expr body = 4;</code>
   */
  com.sstewartgallus.peacod.ast.ExprOrBuilder getBodyOrBuilder();
}
