// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

/**
 * <pre>
 * Fixme, just rename Def or something
 * </pre>
 *
 * Protobuf type {@code peacod_ast.FunctionDef}
 */
public  final class FunctionDef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:peacod_ast.FunctionDef)
    FunctionDefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FunctionDef.newBuilder() to construct.
  private FunctionDef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FunctionDef() {
    name_ = "";
    numTypeParams_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FunctionDef(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            numTypeParams_ = input.readUInt32();
            break;
          }
          case 26: {
            com.sstewartgallus.peacod.ast.TypeExpr.Builder subBuilder = null;
            if (type_ != null) {
              subBuilder = type_.toBuilder();
            }
            type_ = input.readMessage(com.sstewartgallus.peacod.ast.TypeExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(type_);
              type_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.sstewartgallus.peacod.ast.Expr.Builder subBuilder = null;
            if (body_ != null) {
              subBuilder = body_.toBuilder();
            }
            body_ = input.readMessage(com.sstewartgallus.peacod.ast.Expr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(body_);
              body_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_FunctionDef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_FunctionDef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sstewartgallus.peacod.ast.FunctionDef.class, com.sstewartgallus.peacod.ast.FunctionDef.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_TYPE_PARAMS_FIELD_NUMBER = 2;
  private int numTypeParams_;
  /**
   * <code>uint32 num_type_params = 2;</code>
   */
  public int getNumTypeParams() {
    return numTypeParams_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private com.sstewartgallus.peacod.ast.TypeExpr type_;
  /**
   * <code>.peacod_ast.TypeExpr type = 3;</code>
   */
  public boolean hasType() {
    return type_ != null;
  }
  /**
   * <code>.peacod_ast.TypeExpr type = 3;</code>
   */
  public com.sstewartgallus.peacod.ast.TypeExpr getType() {
    return type_ == null ? com.sstewartgallus.peacod.ast.TypeExpr.getDefaultInstance() : type_;
  }
  /**
   * <code>.peacod_ast.TypeExpr type = 3;</code>
   */
  public com.sstewartgallus.peacod.ast.TypeExprOrBuilder getTypeOrBuilder() {
    return getType();
  }

  public static final int BODY_FIELD_NUMBER = 4;
  private com.sstewartgallus.peacod.ast.Expr body_;
  /**
   * <code>.peacod_ast.Expr body = 4;</code>
   */
  public boolean hasBody() {
    return body_ != null;
  }
  /**
   * <code>.peacod_ast.Expr body = 4;</code>
   */
  public com.sstewartgallus.peacod.ast.Expr getBody() {
    return body_ == null ? com.sstewartgallus.peacod.ast.Expr.getDefaultInstance() : body_;
  }
  /**
   * <code>.peacod_ast.Expr body = 4;</code>
   */
  public com.sstewartgallus.peacod.ast.ExprOrBuilder getBodyOrBuilder() {
    return getBody();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (numTypeParams_ != 0) {
      output.writeUInt32(2, numTypeParams_);
    }
    if (type_ != null) {
      output.writeMessage(3, getType());
    }
    if (body_ != null) {
      output.writeMessage(4, getBody());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (numTypeParams_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, numTypeParams_);
    }
    if (type_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getType());
    }
    if (body_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBody());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sstewartgallus.peacod.ast.FunctionDef)) {
      return super.equals(obj);
    }
    com.sstewartgallus.peacod.ast.FunctionDef other = (com.sstewartgallus.peacod.ast.FunctionDef) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (getNumTypeParams()
        == other.getNumTypeParams());
    result = result && (hasType() == other.hasType());
    if (hasType()) {
      result = result && getType()
          .equals(other.getType());
    }
    result = result && (hasBody() == other.hasBody());
    if (hasBody()) {
      result = result && getBody()
          .equals(other.getBody());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + NUM_TYPE_PARAMS_FIELD_NUMBER;
    hash = (53 * hash) + getNumTypeParams();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.FunctionDef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sstewartgallus.peacod.ast.FunctionDef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Fixme, just rename Def or something
   * </pre>
   *
   * Protobuf type {@code peacod_ast.FunctionDef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:peacod_ast.FunctionDef)
      com.sstewartgallus.peacod.ast.FunctionDefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_FunctionDef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_FunctionDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sstewartgallus.peacod.ast.FunctionDef.class, com.sstewartgallus.peacod.ast.FunctionDef.Builder.class);
    }

    // Construct using com.sstewartgallus.peacod.ast.FunctionDef.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      numTypeParams_ = 0;

      if (typeBuilder_ == null) {
        type_ = null;
      } else {
        type_ = null;
        typeBuilder_ = null;
      }
      if (bodyBuilder_ == null) {
        body_ = null;
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_FunctionDef_descriptor;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.FunctionDef getDefaultInstanceForType() {
      return com.sstewartgallus.peacod.ast.FunctionDef.getDefaultInstance();
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.FunctionDef build() {
      com.sstewartgallus.peacod.ast.FunctionDef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.FunctionDef buildPartial() {
      com.sstewartgallus.peacod.ast.FunctionDef result = new com.sstewartgallus.peacod.ast.FunctionDef(this);
      result.name_ = name_;
      result.numTypeParams_ = numTypeParams_;
      if (typeBuilder_ == null) {
        result.type_ = type_;
      } else {
        result.type_ = typeBuilder_.build();
      }
      if (bodyBuilder_ == null) {
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sstewartgallus.peacod.ast.FunctionDef) {
        return mergeFrom((com.sstewartgallus.peacod.ast.FunctionDef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sstewartgallus.peacod.ast.FunctionDef other) {
      if (other == com.sstewartgallus.peacod.ast.FunctionDef.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getNumTypeParams() != 0) {
        setNumTypeParams(other.getNumTypeParams());
      }
      if (other.hasType()) {
        mergeType(other.getType());
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sstewartgallus.peacod.ast.FunctionDef parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sstewartgallus.peacod.ast.FunctionDef) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int numTypeParams_ ;
    /**
     * <code>uint32 num_type_params = 2;</code>
     */
    public int getNumTypeParams() {
      return numTypeParams_;
    }
    /**
     * <code>uint32 num_type_params = 2;</code>
     */
    public Builder setNumTypeParams(int value) {
      
      numTypeParams_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 num_type_params = 2;</code>
     */
    public Builder clearNumTypeParams() {
      
      numTypeParams_ = 0;
      onChanged();
      return this;
    }

    private com.sstewartgallus.peacod.ast.TypeExpr type_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.TypeExpr, com.sstewartgallus.peacod.ast.TypeExpr.Builder, com.sstewartgallus.peacod.ast.TypeExprOrBuilder> typeBuilder_;
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public boolean hasType() {
      return typeBuilder_ != null || type_ != null;
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr getType() {
      if (typeBuilder_ == null) {
        return type_ == null ? com.sstewartgallus.peacod.ast.TypeExpr.getDefaultInstance() : type_;
      } else {
        return typeBuilder_.getMessage();
      }
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public Builder setType(com.sstewartgallus.peacod.ast.TypeExpr value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        typeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public Builder setType(
        com.sstewartgallus.peacod.ast.TypeExpr.Builder builderForValue) {
      if (typeBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        typeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public Builder mergeType(com.sstewartgallus.peacod.ast.TypeExpr value) {
      if (typeBuilder_ == null) {
        if (type_ != null) {
          type_ =
            com.sstewartgallus.peacod.ast.TypeExpr.newBuilder(type_).mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        typeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public Builder clearType() {
      if (typeBuilder_ == null) {
        type_ = null;
        onChanged();
      } else {
        type_ = null;
        typeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr.Builder getTypeBuilder() {
      
      onChanged();
      return getTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExprOrBuilder getTypeOrBuilder() {
      if (typeBuilder_ != null) {
        return typeBuilder_.getMessageOrBuilder();
      } else {
        return type_ == null ?
            com.sstewartgallus.peacod.ast.TypeExpr.getDefaultInstance() : type_;
      }
    }
    /**
     * <code>.peacod_ast.TypeExpr type = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.TypeExpr, com.sstewartgallus.peacod.ast.TypeExpr.Builder, com.sstewartgallus.peacod.ast.TypeExprOrBuilder> 
        getTypeFieldBuilder() {
      if (typeBuilder_ == null) {
        typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sstewartgallus.peacod.ast.TypeExpr, com.sstewartgallus.peacod.ast.TypeExpr.Builder, com.sstewartgallus.peacod.ast.TypeExprOrBuilder>(
                getType(),
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      return typeBuilder_;
    }

    private com.sstewartgallus.peacod.ast.Expr body_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.Expr, com.sstewartgallus.peacod.ast.Expr.Builder, com.sstewartgallus.peacod.ast.ExprOrBuilder> bodyBuilder_;
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public boolean hasBody() {
      return bodyBuilder_ != null || body_ != null;
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public com.sstewartgallus.peacod.ast.Expr getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? com.sstewartgallus.peacod.ast.Expr.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public Builder setBody(com.sstewartgallus.peacod.ast.Expr value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        bodyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public Builder setBody(
        com.sstewartgallus.peacod.ast.Expr.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public Builder mergeBody(com.sstewartgallus.peacod.ast.Expr value) {
      if (bodyBuilder_ == null) {
        if (body_ != null) {
          body_ =
            com.sstewartgallus.peacod.ast.Expr.newBuilder(body_).mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        bodyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = null;
        onChanged();
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public com.sstewartgallus.peacod.ast.Expr.Builder getBodyBuilder() {
      
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    public com.sstewartgallus.peacod.ast.ExprOrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            com.sstewartgallus.peacod.ast.Expr.getDefaultInstance() : body_;
      }
    }
    /**
     * <code>.peacod_ast.Expr body = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.Expr, com.sstewartgallus.peacod.ast.Expr.Builder, com.sstewartgallus.peacod.ast.ExprOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sstewartgallus.peacod.ast.Expr, com.sstewartgallus.peacod.ast.Expr.Builder, com.sstewartgallus.peacod.ast.ExprOrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:peacod_ast.FunctionDef)
  }

  // @@protoc_insertion_point(class_scope:peacod_ast.FunctionDef)
  private static final com.sstewartgallus.peacod.ast.FunctionDef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sstewartgallus.peacod.ast.FunctionDef();
  }

  public static com.sstewartgallus.peacod.ast.FunctionDef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FunctionDef>
      PARSER = new com.google.protobuf.AbstractParser<FunctionDef>() {
    @java.lang.Override
    public FunctionDef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FunctionDef(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FunctionDef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FunctionDef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sstewartgallus.peacod.ast.FunctionDef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

