// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

public interface LibraryDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:peacod_ast.LibraryDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 version = 1;</code>
   */
  int getVersion();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  java.util.List<com.sstewartgallus.peacod.ast.FunctionDef> 
      getFunctionList();
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  com.sstewartgallus.peacod.ast.FunctionDef getFunction(int index);
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  int getFunctionCount();
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  java.util.List<? extends com.sstewartgallus.peacod.ast.FunctionDefOrBuilder> 
      getFunctionOrBuilderList();
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  com.sstewartgallus.peacod.ast.FunctionDefOrBuilder getFunctionOrBuilder(
      int index);
}
