// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

/**
 * Protobuf type {@code peacod_ast.LibraryDef}
 */
public final class LibraryDef extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:peacod_ast.LibraryDef)
        LibraryDefOrBuilder {
    public static final int VERSION_FIELD_NUMBER = 1;
    public static final int NAME_FIELD_NUMBER = 2;
    public static final int DEF_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:peacod_ast.LibraryDef)
    private static final com.sstewartgallus.peacod.ast.LibraryDef DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<LibraryDef>
            PARSER = new com.google.protobuf.AbstractParser<LibraryDef>() {
        @java.lang.Override
        public LibraryDef parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new LibraryDef(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.sstewartgallus.peacod.ast.LibraryDef();
    }

    private int version_;
    private volatile java.lang.Object name_;
    private com.google.protobuf.MapField<
            java.lang.String, com.sstewartgallus.peacod.ast.Def> def_;
    private byte memoizedIsInitialized = -1;

    // Use LibraryDef.newBuilder() to construct.
    private LibraryDef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private LibraryDef() {
        name_ = "";
    }
    private LibraryDef(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 8: {

                        version_ = input.readUInt32();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        name_ = s;
                        break;
                    }
                    case 26: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            def_ = com.google.protobuf.MapField.newMapField(
                                    DefDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000001;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, com.sstewartgallus.peacod.ast.Def>
                                def__ = input.readMessage(
                                DefDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                        def_.getMutableMap().put(
                                def__.getKey(), def__.getValue());
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_descriptor;
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.sstewartgallus.peacod.ast.LibraryDef prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.sstewartgallus.peacod.ast.LibraryDef getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<LibraryDef> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new LibraryDef();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
        switch (number) {
            case 3:
                return internalGetDef();
            default:
                throw new RuntimeException(
                        "Invalid map field number: " + number);
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.sstewartgallus.peacod.ast.LibraryDef.class, com.sstewartgallus.peacod.ast.LibraryDef.Builder.class);
    }

    /**
     * <code>uint32 version = 1;</code>
     *
     * @return The version.
     */
    public int getVersion() {
        return version_;
    }

    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private com.google.protobuf.MapField<java.lang.String, com.sstewartgallus.peacod.ast.Def>
    internalGetDef() {
        if (def_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    DefDefaultEntryHolder.defaultEntry);
        }
        return def_;
    }

    public int getDefCount() {
        return internalGetDef().getMap().size();
    }

    /**
     * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
     */

    public boolean containsDef(
            java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetDef().getMap().containsKey(key);
    }

    /**
     * Use {@link #getDefMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> getDef() {
        return getDefMap();
    }

    /**
     * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
     */

    public java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> getDefMap() {
        return internalGetDef().getMap();
    }

    /**
     * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
     */

    public com.sstewartgallus.peacod.ast.Def getDefOrDefault(
            java.lang.String key,
            com.sstewartgallus.peacod.ast.Def defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> map =
                internalGetDef().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
     */

    public com.sstewartgallus.peacod.ast.Def getDefOrThrow(
            java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> map =
                internalGetDef().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (version_ != 0) {
            output.writeUInt32(1, version_);
        }
        if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(
                        output,
                        internalGetDef(),
                        DefDefaultEntryHolder.defaultEntry,
                        3);
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (version_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt32Size(1, version_);
        }
        if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        for (java.util.Map.Entry<java.lang.String, com.sstewartgallus.peacod.ast.Def> entry
                : internalGetDef().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, com.sstewartgallus.peacod.ast.Def>
                    def__ = DefDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, def__);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.sstewartgallus.peacod.ast.LibraryDef)) {
            return super.equals(obj);
        }
        com.sstewartgallus.peacod.ast.LibraryDef other = (com.sstewartgallus.peacod.ast.LibraryDef) obj;

        if (getVersion()
                != other.getVersion()) return false;
        if (!getName()
                .equals(other.getName())) return false;
        if (!internalGetDef().equals(
                other.internalGetDef())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        if (!internalGetDef().getMap().isEmpty()) {
            hash = (37 * hash) + DEF_FIELD_NUMBER;
            hash = (53 * hash) + internalGetDef().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LibraryDef> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.LibraryDef getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    private static final class DefDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.String, com.sstewartgallus.peacod.ast.Def> defaultEntry =
                com.google.protobuf.MapEntry
                        .<java.lang.String, com.sstewartgallus.peacod.ast.Def>newDefaultInstance(
                                com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_DefEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "",
                                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                com.sstewartgallus.peacod.ast.Def.getDefaultInstance());
    }

    /**
     * Protobuf type {@code peacod_ast.LibraryDef}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:peacod_ast.LibraryDef)
            com.sstewartgallus.peacod.ast.LibraryDefOrBuilder {
        private int bitField0_;
        private int version_;
        private java.lang.Object name_ = "";
        private com.google.protobuf.MapField<
                java.lang.String, com.sstewartgallus.peacod.ast.Def> def_;

        // Construct using com.sstewartgallus.peacod.ast.LibraryDef.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 3:
                    return internalGetDef();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
                int number) {
            switch (number) {
                case 3:
                    return internalGetMutableDef();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.sstewartgallus.peacod.ast.LibraryDef.class, com.sstewartgallus.peacod.ast.LibraryDef.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            version_ = 0;

            name_ = "";

            internalGetMutableDef().clear();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_descriptor;
        }

        @java.lang.Override
        public com.sstewartgallus.peacod.ast.LibraryDef getDefaultInstanceForType() {
            return com.sstewartgallus.peacod.ast.LibraryDef.getDefaultInstance();
        }

        @java.lang.Override
        public com.sstewartgallus.peacod.ast.LibraryDef build() {
            com.sstewartgallus.peacod.ast.LibraryDef result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.sstewartgallus.peacod.ast.LibraryDef buildPartial() {
            com.sstewartgallus.peacod.ast.LibraryDef result = new com.sstewartgallus.peacod.ast.LibraryDef(this);
            int from_bitField0_ = bitField0_;
            result.version_ = version_;
            result.name_ = name_;
            result.def_ = internalGetDef();
            result.def_.makeImmutable();
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.sstewartgallus.peacod.ast.LibraryDef) {
                return mergeFrom((com.sstewartgallus.peacod.ast.LibraryDef) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.sstewartgallus.peacod.ast.LibraryDef other) {
            if (other == com.sstewartgallus.peacod.ast.LibraryDef.getDefaultInstance()) return this;
            if (other.getVersion() != 0) {
                setVersion(other.getVersion());
            }
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                onChanged();
            }
            internalGetMutableDef().mergeFrom(
                    other.internalGetDef());
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.sstewartgallus.peacod.ast.LibraryDef parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.sstewartgallus.peacod.ast.LibraryDef) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>uint32 version = 1;</code>
         *
         * @return The version.
         */
        public int getVersion() {
            return version_;
        }

        /**
         * <code>uint32 version = 1;</code>
         *
         * @param value The version to set.
         * @return This builder for chaining.
         */
        public Builder setVersion(int value) {

            version_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>uint32 version = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearVersion() {

            version_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         *
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         *
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearName() {

            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        private com.google.protobuf.MapField<java.lang.String, com.sstewartgallus.peacod.ast.Def>
        internalGetDef() {
            if (def_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        DefDefaultEntryHolder.defaultEntry);
            }
            return def_;
        }

        private com.google.protobuf.MapField<java.lang.String, com.sstewartgallus.peacod.ast.Def>
        internalGetMutableDef() {
            onChanged();
            ;
            if (def_ == null) {
                def_ = com.google.protobuf.MapField.newMapField(
                        DefDefaultEntryHolder.defaultEntry);
            }
            if (!def_.isMutable()) {
                def_ = def_.copy();
            }
            return def_;
        }

        public int getDefCount() {
            return internalGetDef().getMap().size();
        }

        /**
         * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
         */

        public boolean containsDef(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetDef().getMap().containsKey(key);
        }

        /**
         * Use {@link #getDefMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> getDef() {
            return getDefMap();
        }

        /**
         * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
         */

        public java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> getDefMap() {
            return internalGetDef().getMap();
        }

        /**
         * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
         */

        public com.sstewartgallus.peacod.ast.Def getDefOrDefault(
                java.lang.String key,
                com.sstewartgallus.peacod.ast.Def defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> map =
                    internalGetDef().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
         */

        public com.sstewartgallus.peacod.ast.Def getDefOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> map =
                    internalGetDef().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearDef() {
            internalGetMutableDef().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
         */

        public Builder removeDef(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableDef().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def>
        getMutableDef() {
            return internalGetMutableDef().getMutableMap();
        }

        /**
         * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
         */
        public Builder putDef(
                java.lang.String key,
                com.sstewartgallus.peacod.ast.Def value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableDef().getMutableMap()
                    .put(key, value);
            return this;
        }

        /**
         * <code>map&lt;string, .peacod_ast.Def&gt; def = 3;</code>
         */

        public Builder putAllDef(
                java.util.Map<java.lang.String, com.sstewartgallus.peacod.ast.Def> values) {
            internalGetMutableDef().getMutableMap()
                    .putAll(values);
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:peacod_ast.LibraryDef)
    }

}

