// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

/**
 * Protobuf type {@code peacod_ast.LibraryDef}
 */
public  final class LibraryDef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:peacod_ast.LibraryDef)
    LibraryDefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LibraryDef.newBuilder() to construct.
  private LibraryDef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LibraryDef() {
    version_ = 0;
    name_ = "";
    function_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LibraryDef(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              function_ = new java.util.ArrayList<com.sstewartgallus.peacod.ast.FunctionDef>();
              mutable_bitField0_ |= 0x00000004;
            }
            function_.add(
                input.readMessage(com.sstewartgallus.peacod.ast.FunctionDef.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        function_ = java.util.Collections.unmodifiableList(function_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sstewartgallus.peacod.ast.LibraryDef.class, com.sstewartgallus.peacod.ast.LibraryDef.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>uint32 version = 1;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNCTION_FIELD_NUMBER = 3;
  private java.util.List<com.sstewartgallus.peacod.ast.FunctionDef> function_;
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  public java.util.List<com.sstewartgallus.peacod.ast.FunctionDef> getFunctionList() {
    return function_;
  }
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  public java.util.List<? extends com.sstewartgallus.peacod.ast.FunctionDefOrBuilder> 
      getFunctionOrBuilderList() {
    return function_;
  }
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  public int getFunctionCount() {
    return function_.size();
  }
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  public com.sstewartgallus.peacod.ast.FunctionDef getFunction(int index) {
    return function_.get(index);
  }
  /**
   * <pre>
   * fixme consider map?
   * </pre>
   *
   * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
   */
  public com.sstewartgallus.peacod.ast.FunctionDefOrBuilder getFunctionOrBuilder(
      int index) {
    return function_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeUInt32(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    for (int i = 0; i < function_.size(); i++) {
      output.writeMessage(3, function_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    for (int i = 0; i < function_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, function_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sstewartgallus.peacod.ast.LibraryDef)) {
      return super.equals(obj);
    }
    com.sstewartgallus.peacod.ast.LibraryDef other = (com.sstewartgallus.peacod.ast.LibraryDef) obj;

    boolean result = true;
    result = result && (getVersion()
        == other.getVersion());
    result = result && getName()
        .equals(other.getName());
    result = result && getFunctionList()
        .equals(other.getFunctionList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getFunctionCount() > 0) {
      hash = (37 * hash) + FUNCTION_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.LibraryDef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sstewartgallus.peacod.ast.LibraryDef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code peacod_ast.LibraryDef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:peacod_ast.LibraryDef)
      com.sstewartgallus.peacod.ast.LibraryDefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sstewartgallus.peacod.ast.LibraryDef.class, com.sstewartgallus.peacod.ast.LibraryDef.Builder.class);
    }

    // Construct using com.sstewartgallus.peacod.ast.LibraryDef.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFunctionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      name_ = "";

      if (functionBuilder_ == null) {
        function_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        functionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_LibraryDef_descriptor;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.LibraryDef getDefaultInstanceForType() {
      return com.sstewartgallus.peacod.ast.LibraryDef.getDefaultInstance();
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.LibraryDef build() {
      com.sstewartgallus.peacod.ast.LibraryDef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.LibraryDef buildPartial() {
      com.sstewartgallus.peacod.ast.LibraryDef result = new com.sstewartgallus.peacod.ast.LibraryDef(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      result.name_ = name_;
      if (functionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          function_ = java.util.Collections.unmodifiableList(function_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.function_ = function_;
      } else {
        result.function_ = functionBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sstewartgallus.peacod.ast.LibraryDef) {
        return mergeFrom((com.sstewartgallus.peacod.ast.LibraryDef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sstewartgallus.peacod.ast.LibraryDef other) {
      if (other == com.sstewartgallus.peacod.ast.LibraryDef.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (functionBuilder_ == null) {
        if (!other.function_.isEmpty()) {
          if (function_.isEmpty()) {
            function_ = other.function_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFunctionIsMutable();
            function_.addAll(other.function_);
          }
          onChanged();
        }
      } else {
        if (!other.function_.isEmpty()) {
          if (functionBuilder_.isEmpty()) {
            functionBuilder_.dispose();
            functionBuilder_ = null;
            function_ = other.function_;
            bitField0_ = (bitField0_ & ~0x00000004);
            functionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFunctionFieldBuilder() : null;
          } else {
            functionBuilder_.addAllMessages(other.function_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sstewartgallus.peacod.ast.LibraryDef parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sstewartgallus.peacod.ast.LibraryDef) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>uint32 version = 1;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 version = 1;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.sstewartgallus.peacod.ast.FunctionDef> function_ =
      java.util.Collections.emptyList();
    private void ensureFunctionIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        function_ = new java.util.ArrayList<com.sstewartgallus.peacod.ast.FunctionDef>(function_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sstewartgallus.peacod.ast.FunctionDef, com.sstewartgallus.peacod.ast.FunctionDef.Builder, com.sstewartgallus.peacod.ast.FunctionDefOrBuilder> functionBuilder_;

    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public java.util.List<com.sstewartgallus.peacod.ast.FunctionDef> getFunctionList() {
      if (functionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(function_);
      } else {
        return functionBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public int getFunctionCount() {
      if (functionBuilder_ == null) {
        return function_.size();
      } else {
        return functionBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.FunctionDef getFunction(int index) {
      if (functionBuilder_ == null) {
        return function_.get(index);
      } else {
        return functionBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder setFunction(
        int index, com.sstewartgallus.peacod.ast.FunctionDef value) {
      if (functionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionIsMutable();
        function_.set(index, value);
        onChanged();
      } else {
        functionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder setFunction(
        int index, com.sstewartgallus.peacod.ast.FunctionDef.Builder builderForValue) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.set(index, builderForValue.build());
        onChanged();
      } else {
        functionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder addFunction(com.sstewartgallus.peacod.ast.FunctionDef value) {
      if (functionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionIsMutable();
        function_.add(value);
        onChanged();
      } else {
        functionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder addFunction(
        int index, com.sstewartgallus.peacod.ast.FunctionDef value) {
      if (functionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionIsMutable();
        function_.add(index, value);
        onChanged();
      } else {
        functionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder addFunction(
        com.sstewartgallus.peacod.ast.FunctionDef.Builder builderForValue) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.add(builderForValue.build());
        onChanged();
      } else {
        functionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder addFunction(
        int index, com.sstewartgallus.peacod.ast.FunctionDef.Builder builderForValue) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.add(index, builderForValue.build());
        onChanged();
      } else {
        functionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder addAllFunction(
        java.lang.Iterable<? extends com.sstewartgallus.peacod.ast.FunctionDef> values) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, function_);
        onChanged();
      } else {
        functionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder clearFunction() {
      if (functionBuilder_ == null) {
        function_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        functionBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public Builder removeFunction(int index) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.remove(index);
        onChanged();
      } else {
        functionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.FunctionDef.Builder getFunctionBuilder(
        int index) {
      return getFunctionFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.FunctionDefOrBuilder getFunctionOrBuilder(
        int index) {
      if (functionBuilder_ == null) {
        return function_.get(index);  } else {
        return functionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public java.util.List<? extends com.sstewartgallus.peacod.ast.FunctionDefOrBuilder> 
         getFunctionOrBuilderList() {
      if (functionBuilder_ != null) {
        return functionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(function_);
      }
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.FunctionDef.Builder addFunctionBuilder() {
      return getFunctionFieldBuilder().addBuilder(
          com.sstewartgallus.peacod.ast.FunctionDef.getDefaultInstance());
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.FunctionDef.Builder addFunctionBuilder(
        int index) {
      return getFunctionFieldBuilder().addBuilder(
          index, com.sstewartgallus.peacod.ast.FunctionDef.getDefaultInstance());
    }
    /**
     * <pre>
     * fixme consider map?
     * </pre>
     *
     * <code>repeated .peacod_ast.FunctionDef function = 3;</code>
     */
    public java.util.List<com.sstewartgallus.peacod.ast.FunctionDef.Builder> 
         getFunctionBuilderList() {
      return getFunctionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sstewartgallus.peacod.ast.FunctionDef, com.sstewartgallus.peacod.ast.FunctionDef.Builder, com.sstewartgallus.peacod.ast.FunctionDefOrBuilder> 
        getFunctionFieldBuilder() {
      if (functionBuilder_ == null) {
        functionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sstewartgallus.peacod.ast.FunctionDef, com.sstewartgallus.peacod.ast.FunctionDef.Builder, com.sstewartgallus.peacod.ast.FunctionDefOrBuilder>(
                function_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        function_ = null;
      }
      return functionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:peacod_ast.LibraryDef)
  }

  // @@protoc_insertion_point(class_scope:peacod_ast.LibraryDef)
  private static final com.sstewartgallus.peacod.ast.LibraryDef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sstewartgallus.peacod.ast.LibraryDef();
  }

  public static com.sstewartgallus.peacod.ast.LibraryDef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LibraryDef>
      PARSER = new com.google.protobuf.AbstractParser<LibraryDef>() {
    @java.lang.Override
    public LibraryDef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LibraryDef(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LibraryDef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LibraryDef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sstewartgallus.peacod.ast.LibraryDef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

