// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ast/src/main/ast.proto

package com.sstewartgallus.peacod.ast;

/**
 * <pre>
 * FIXME: Rename as Type
 * </pre>
 *
 * Protobuf type {@code peacod_ast.TypeExpr}
 */
public  final class TypeExpr extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:peacod_ast.TypeExpr)
    TypeExprOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TypeExpr.newBuilder() to construct.
  private TypeExpr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TypeExpr() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TypeExpr(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder subBuilder = null;
            if (valueCase_ == 1) {
              subBuilder = ((com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_).toBuilder();
            }
            value_ =
                input.readMessage(com.sstewartgallus.peacod.ast.TypeExpr.Literal.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_);
              value_ = subBuilder.buildPartial();
            }
            valueCase_ = 1;
            break;
          }
          case 18: {
            com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder subBuilder = null;
            if (valueCase_ == 2) {
              subBuilder = ((com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_).toBuilder();
            }
            value_ =
                input.readMessage(com.sstewartgallus.peacod.ast.TypeExpr.Variable.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_);
              value_ = subBuilder.buildPartial();
            }
            valueCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sstewartgallus.peacod.ast.TypeExpr.class, com.sstewartgallus.peacod.ast.TypeExpr.Builder.class);
  }

  public interface LiteralOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peacod_ast.TypeExpr.Literal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string library = 1;</code>
     */
    java.lang.String getLibrary();
    /**
     * <code>string library = 1;</code>
     */
    com.google.protobuf.ByteString
        getLibraryBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    java.util.List<com.sstewartgallus.peacod.ast.TypeExpr> 
        getArgumentList();
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    com.sstewartgallus.peacod.ast.TypeExpr getArgument(int index);
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    int getArgumentCount();
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    java.util.List<? extends com.sstewartgallus.peacod.ast.TypeExprOrBuilder> 
        getArgumentOrBuilderList();
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    com.sstewartgallus.peacod.ast.TypeExprOrBuilder getArgumentOrBuilder(
        int index);
  }
  /**
   * <pre>
   * FIXME? arity
   * </pre>
   *
   * Protobuf type {@code peacod_ast.TypeExpr.Literal}
   */
  public  static final class Literal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:peacod_ast.TypeExpr.Literal)
      LiteralOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Literal.newBuilder() to construct.
    private Literal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Literal() {
      library_ = "";
      name_ = "";
      argument_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Literal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              library_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                argument_ = new java.util.ArrayList<com.sstewartgallus.peacod.ast.TypeExpr>();
                mutable_bitField0_ |= 0x00000004;
              }
              argument_.add(
                  input.readMessage(com.sstewartgallus.peacod.ast.TypeExpr.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          argument_ = java.util.Collections.unmodifiableList(argument_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Literal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Literal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sstewartgallus.peacod.ast.TypeExpr.Literal.class, com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder.class);
    }

    private int bitField0_;
    public static final int LIBRARY_FIELD_NUMBER = 1;
    private volatile java.lang.Object library_;
    /**
     * <code>string library = 1;</code>
     */
    public java.lang.String getLibrary() {
      java.lang.Object ref = library_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        library_ = s;
        return s;
      }
    }
    /**
     * <code>string library = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLibraryBytes() {
      java.lang.Object ref = library_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        library_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGUMENT_FIELD_NUMBER = 3;
    private java.util.List<com.sstewartgallus.peacod.ast.TypeExpr> argument_;
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    public java.util.List<com.sstewartgallus.peacod.ast.TypeExpr> getArgumentList() {
      return argument_;
    }
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    public java.util.List<? extends com.sstewartgallus.peacod.ast.TypeExprOrBuilder> 
        getArgumentOrBuilderList() {
      return argument_;
    }
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    public int getArgumentCount() {
      return argument_.size();
    }
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr getArgument(int index) {
      return argument_.get(index);
    }
    /**
     * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExprOrBuilder getArgumentOrBuilder(
        int index) {
      return argument_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLibraryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, library_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < argument_.size(); i++) {
        output.writeMessage(3, argument_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLibraryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, library_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < argument_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, argument_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sstewartgallus.peacod.ast.TypeExpr.Literal)) {
        return super.equals(obj);
      }
      com.sstewartgallus.peacod.ast.TypeExpr.Literal other = (com.sstewartgallus.peacod.ast.TypeExpr.Literal) obj;

      boolean result = true;
      result = result && getLibrary()
          .equals(other.getLibrary());
      result = result && getName()
          .equals(other.getName());
      result = result && getArgumentList()
          .equals(other.getArgumentList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIBRARY_FIELD_NUMBER;
      hash = (53 * hash) + getLibrary().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getArgumentCount() > 0) {
        hash = (37 * hash) + ARGUMENT_FIELD_NUMBER;
        hash = (53 * hash) + getArgumentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sstewartgallus.peacod.ast.TypeExpr.Literal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * FIXME? arity
     * </pre>
     *
     * Protobuf type {@code peacod_ast.TypeExpr.Literal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:peacod_ast.TypeExpr.Literal)
        com.sstewartgallus.peacod.ast.TypeExpr.LiteralOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Literal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Literal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sstewartgallus.peacod.ast.TypeExpr.Literal.class, com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder.class);
      }

      // Construct using com.sstewartgallus.peacod.ast.TypeExpr.Literal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArgumentFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        library_ = "";

        name_ = "";

        if (argumentBuilder_ == null) {
          argument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          argumentBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Literal_descriptor;
      }

      @java.lang.Override
      public com.sstewartgallus.peacod.ast.TypeExpr.Literal getDefaultInstanceForType() {
        return com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance();
      }

      @java.lang.Override
      public com.sstewartgallus.peacod.ast.TypeExpr.Literal build() {
        com.sstewartgallus.peacod.ast.TypeExpr.Literal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sstewartgallus.peacod.ast.TypeExpr.Literal buildPartial() {
        com.sstewartgallus.peacod.ast.TypeExpr.Literal result = new com.sstewartgallus.peacod.ast.TypeExpr.Literal(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.library_ = library_;
        result.name_ = name_;
        if (argumentBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            argument_ = java.util.Collections.unmodifiableList(argument_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.argument_ = argument_;
        } else {
          result.argument_ = argumentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sstewartgallus.peacod.ast.TypeExpr.Literal) {
          return mergeFrom((com.sstewartgallus.peacod.ast.TypeExpr.Literal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sstewartgallus.peacod.ast.TypeExpr.Literal other) {
        if (other == com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance()) return this;
        if (!other.getLibrary().isEmpty()) {
          library_ = other.library_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (argumentBuilder_ == null) {
          if (!other.argument_.isEmpty()) {
            if (argument_.isEmpty()) {
              argument_ = other.argument_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureArgumentIsMutable();
              argument_.addAll(other.argument_);
            }
            onChanged();
          }
        } else {
          if (!other.argument_.isEmpty()) {
            if (argumentBuilder_.isEmpty()) {
              argumentBuilder_.dispose();
              argumentBuilder_ = null;
              argument_ = other.argument_;
              bitField0_ = (bitField0_ & ~0x00000004);
              argumentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArgumentFieldBuilder() : null;
            } else {
              argumentBuilder_.addAllMessages(other.argument_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sstewartgallus.peacod.ast.TypeExpr.Literal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sstewartgallus.peacod.ast.TypeExpr.Literal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object library_ = "";
      /**
       * <code>string library = 1;</code>
       */
      public java.lang.String getLibrary() {
        java.lang.Object ref = library_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          library_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string library = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLibraryBytes() {
        java.lang.Object ref = library_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          library_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string library = 1;</code>
       */
      public Builder setLibrary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        library_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string library = 1;</code>
       */
      public Builder clearLibrary() {
        
        library_ = getDefaultInstance().getLibrary();
        onChanged();
        return this;
      }
      /**
       * <code>string library = 1;</code>
       */
      public Builder setLibraryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        library_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.sstewartgallus.peacod.ast.TypeExpr> argument_ =
        java.util.Collections.emptyList();
      private void ensureArgumentIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          argument_ = new java.util.ArrayList<com.sstewartgallus.peacod.ast.TypeExpr>(argument_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sstewartgallus.peacod.ast.TypeExpr, com.sstewartgallus.peacod.ast.TypeExpr.Builder, com.sstewartgallus.peacod.ast.TypeExprOrBuilder> argumentBuilder_;

      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public java.util.List<com.sstewartgallus.peacod.ast.TypeExpr> getArgumentList() {
        if (argumentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(argument_);
        } else {
          return argumentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public int getArgumentCount() {
        if (argumentBuilder_ == null) {
          return argument_.size();
        } else {
          return argumentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public com.sstewartgallus.peacod.ast.TypeExpr getArgument(int index) {
        if (argumentBuilder_ == null) {
          return argument_.get(index);
        } else {
          return argumentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder setArgument(
          int index, com.sstewartgallus.peacod.ast.TypeExpr value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.set(index, value);
          onChanged();
        } else {
          argumentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder setArgument(
          int index, com.sstewartgallus.peacod.ast.TypeExpr.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.set(index, builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder addArgument(com.sstewartgallus.peacod.ast.TypeExpr value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.add(value);
          onChanged();
        } else {
          argumentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder addArgument(
          int index, com.sstewartgallus.peacod.ast.TypeExpr value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.add(index, value);
          onChanged();
        } else {
          argumentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder addArgument(
          com.sstewartgallus.peacod.ast.TypeExpr.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.add(builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder addArgument(
          int index, com.sstewartgallus.peacod.ast.TypeExpr.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.add(index, builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder addAllArgument(
          java.lang.Iterable<? extends com.sstewartgallus.peacod.ast.TypeExpr> values) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, argument_);
          onChanged();
        } else {
          argumentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder clearArgument() {
        if (argumentBuilder_ == null) {
          argument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          argumentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public Builder removeArgument(int index) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.remove(index);
          onChanged();
        } else {
          argumentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public com.sstewartgallus.peacod.ast.TypeExpr.Builder getArgumentBuilder(
          int index) {
        return getArgumentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public com.sstewartgallus.peacod.ast.TypeExprOrBuilder getArgumentOrBuilder(
          int index) {
        if (argumentBuilder_ == null) {
          return argument_.get(index);  } else {
          return argumentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public java.util.List<? extends com.sstewartgallus.peacod.ast.TypeExprOrBuilder> 
           getArgumentOrBuilderList() {
        if (argumentBuilder_ != null) {
          return argumentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(argument_);
        }
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public com.sstewartgallus.peacod.ast.TypeExpr.Builder addArgumentBuilder() {
        return getArgumentFieldBuilder().addBuilder(
            com.sstewartgallus.peacod.ast.TypeExpr.getDefaultInstance());
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public com.sstewartgallus.peacod.ast.TypeExpr.Builder addArgumentBuilder(
          int index) {
        return getArgumentFieldBuilder().addBuilder(
            index, com.sstewartgallus.peacod.ast.TypeExpr.getDefaultInstance());
      }
      /**
       * <code>repeated .peacod_ast.TypeExpr argument = 3;</code>
       */
      public java.util.List<com.sstewartgallus.peacod.ast.TypeExpr.Builder> 
           getArgumentBuilderList() {
        return getArgumentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sstewartgallus.peacod.ast.TypeExpr, com.sstewartgallus.peacod.ast.TypeExpr.Builder, com.sstewartgallus.peacod.ast.TypeExprOrBuilder> 
          getArgumentFieldBuilder() {
        if (argumentBuilder_ == null) {
          argumentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.sstewartgallus.peacod.ast.TypeExpr, com.sstewartgallus.peacod.ast.TypeExpr.Builder, com.sstewartgallus.peacod.ast.TypeExprOrBuilder>(
                  argument_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          argument_ = null;
        }
        return argumentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:peacod_ast.TypeExpr.Literal)
    }

    // @@protoc_insertion_point(class_scope:peacod_ast.TypeExpr.Literal)
    private static final com.sstewartgallus.peacod.ast.TypeExpr.Literal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sstewartgallus.peacod.ast.TypeExpr.Literal();
    }

    public static com.sstewartgallus.peacod.ast.TypeExpr.Literal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Literal>
        PARSER = new com.google.protobuf.AbstractParser<Literal>() {
      @java.lang.Override
      public Literal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Literal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Literal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Literal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.TypeExpr.Literal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VariableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peacod_ast.TypeExpr.Variable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * FIXME... give a kind?
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     */
    int getIndex();
  }
  /**
   * Protobuf type {@code peacod_ast.TypeExpr.Variable}
   */
  public  static final class Variable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:peacod_ast.TypeExpr.Variable)
      VariableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Variable.newBuilder() to construct.
    private Variable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Variable() {
      index_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Variable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Variable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Variable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sstewartgallus.peacod.ast.TypeExpr.Variable.class, com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <pre>
     * FIXME... give a kind?
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeUInt32(1, index_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, index_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sstewartgallus.peacod.ast.TypeExpr.Variable)) {
        return super.equals(obj);
      }
      com.sstewartgallus.peacod.ast.TypeExpr.Variable other = (com.sstewartgallus.peacod.ast.TypeExpr.Variable) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sstewartgallus.peacod.ast.TypeExpr.Variable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code peacod_ast.TypeExpr.Variable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:peacod_ast.TypeExpr.Variable)
        com.sstewartgallus.peacod.ast.TypeExpr.VariableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Variable_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Variable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sstewartgallus.peacod.ast.TypeExpr.Variable.class, com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder.class);
      }

      // Construct using com.sstewartgallus.peacod.ast.TypeExpr.Variable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_Variable_descriptor;
      }

      @java.lang.Override
      public com.sstewartgallus.peacod.ast.TypeExpr.Variable getDefaultInstanceForType() {
        return com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance();
      }

      @java.lang.Override
      public com.sstewartgallus.peacod.ast.TypeExpr.Variable build() {
        com.sstewartgallus.peacod.ast.TypeExpr.Variable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sstewartgallus.peacod.ast.TypeExpr.Variable buildPartial() {
        com.sstewartgallus.peacod.ast.TypeExpr.Variable result = new com.sstewartgallus.peacod.ast.TypeExpr.Variable(this);
        result.index_ = index_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sstewartgallus.peacod.ast.TypeExpr.Variable) {
          return mergeFrom((com.sstewartgallus.peacod.ast.TypeExpr.Variable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sstewartgallus.peacod.ast.TypeExpr.Variable other) {
        if (other == com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sstewartgallus.peacod.ast.TypeExpr.Variable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sstewartgallus.peacod.ast.TypeExpr.Variable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <pre>
       * FIXME... give a kind?
       * </pre>
       *
       * <code>uint32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       * FIXME... give a kind?
       * </pre>
       *
       * <code>uint32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * FIXME... give a kind?
       * </pre>
       *
       * <code>uint32 index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:peacod_ast.TypeExpr.Variable)
    }

    // @@protoc_insertion_point(class_scope:peacod_ast.TypeExpr.Variable)
    private static final com.sstewartgallus.peacod.ast.TypeExpr.Variable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sstewartgallus.peacod.ast.TypeExpr.Variable();
    }

    public static com.sstewartgallus.peacod.ast.TypeExpr.Variable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Variable>
        PARSER = new com.google.protobuf.AbstractParser<Variable>() {
      @java.lang.Override
      public Variable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Variable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Variable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Variable> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.TypeExpr.Variable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite {
    LITERAL(1),
    VARIABLE(2),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 1: return LITERAL;
        case 2: return VARIABLE;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int LITERAL_FIELD_NUMBER = 1;
  /**
   * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
   */
  public boolean hasLiteral() {
    return valueCase_ == 1;
  }
  /**
   * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
   */
  public com.sstewartgallus.peacod.ast.TypeExpr.Literal getLiteral() {
    if (valueCase_ == 1) {
       return (com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_;
    }
    return com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance();
  }
  /**
   * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
   */
  public com.sstewartgallus.peacod.ast.TypeExpr.LiteralOrBuilder getLiteralOrBuilder() {
    if (valueCase_ == 1) {
       return (com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_;
    }
    return com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance();
  }

  public static final int VARIABLE_FIELD_NUMBER = 2;
  /**
   * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
   */
  public boolean hasVariable() {
    return valueCase_ == 2;
  }
  /**
   * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
   */
  public com.sstewartgallus.peacod.ast.TypeExpr.Variable getVariable() {
    if (valueCase_ == 2) {
       return (com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_;
    }
    return com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance();
  }
  /**
   * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
   */
  public com.sstewartgallus.peacod.ast.TypeExpr.VariableOrBuilder getVariableOrBuilder() {
    if (valueCase_ == 2) {
       return (com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_;
    }
    return com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valueCase_ == 1) {
      output.writeMessage(1, (com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_);
    }
    if (valueCase_ == 2) {
      output.writeMessage(2, (com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valueCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sstewartgallus.peacod.ast.TypeExpr)) {
      return super.equals(obj);
    }
    com.sstewartgallus.peacod.ast.TypeExpr other = (com.sstewartgallus.peacod.ast.TypeExpr) obj;

    boolean result = true;
    result = result && getValueCase().equals(
        other.getValueCase());
    if (!result) return false;
    switch (valueCase_) {
      case 1:
        result = result && getLiteral()
            .equals(other.getLiteral());
        break;
      case 2:
        result = result && getVariable()
            .equals(other.getVariable());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (valueCase_) {
      case 1:
        hash = (37 * hash) + LITERAL_FIELD_NUMBER;
        hash = (53 * hash) + getLiteral().hashCode();
        break;
      case 2:
        hash = (37 * hash) + VARIABLE_FIELD_NUMBER;
        hash = (53 * hash) + getVariable().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sstewartgallus.peacod.ast.TypeExpr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sstewartgallus.peacod.ast.TypeExpr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FIXME: Rename as Type
   * </pre>
   *
   * Protobuf type {@code peacod_ast.TypeExpr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:peacod_ast.TypeExpr)
      com.sstewartgallus.peacod.ast.TypeExprOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sstewartgallus.peacod.ast.TypeExpr.class, com.sstewartgallus.peacod.ast.TypeExpr.Builder.class);
    }

    // Construct using com.sstewartgallus.peacod.ast.TypeExpr.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sstewartgallus.peacod.ast.Ast.internal_static_peacod_ast_TypeExpr_descriptor;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.TypeExpr getDefaultInstanceForType() {
      return com.sstewartgallus.peacod.ast.TypeExpr.getDefaultInstance();
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.TypeExpr build() {
      com.sstewartgallus.peacod.ast.TypeExpr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sstewartgallus.peacod.ast.TypeExpr buildPartial() {
      com.sstewartgallus.peacod.ast.TypeExpr result = new com.sstewartgallus.peacod.ast.TypeExpr(this);
      if (valueCase_ == 1) {
        if (literalBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = literalBuilder_.build();
        }
      }
      if (valueCase_ == 2) {
        if (variableBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = variableBuilder_.build();
        }
      }
      result.valueCase_ = valueCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sstewartgallus.peacod.ast.TypeExpr) {
        return mergeFrom((com.sstewartgallus.peacod.ast.TypeExpr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sstewartgallus.peacod.ast.TypeExpr other) {
      if (other == com.sstewartgallus.peacod.ast.TypeExpr.getDefaultInstance()) return this;
      switch (other.getValueCase()) {
        case LITERAL: {
          mergeLiteral(other.getLiteral());
          break;
        }
        case VARIABLE: {
          mergeVariable(other.getVariable());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sstewartgallus.peacod.ast.TypeExpr parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sstewartgallus.peacod.ast.TypeExpr) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.TypeExpr.Literal, com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder, com.sstewartgallus.peacod.ast.TypeExpr.LiteralOrBuilder> literalBuilder_;
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public boolean hasLiteral() {
      return valueCase_ == 1;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr.Literal getLiteral() {
      if (literalBuilder_ == null) {
        if (valueCase_ == 1) {
          return (com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_;
        }
        return com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance();
      } else {
        if (valueCase_ == 1) {
          return literalBuilder_.getMessage();
        }
        return com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance();
      }
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public Builder setLiteral(com.sstewartgallus.peacod.ast.TypeExpr.Literal value) {
      if (literalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        literalBuilder_.setMessage(value);
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public Builder setLiteral(
        com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder builderForValue) {
      if (literalBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        literalBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public Builder mergeLiteral(com.sstewartgallus.peacod.ast.TypeExpr.Literal value) {
      if (literalBuilder_ == null) {
        if (valueCase_ == 1 &&
            value_ != com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance()) {
          value_ = com.sstewartgallus.peacod.ast.TypeExpr.Literal.newBuilder((com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 1) {
          literalBuilder_.mergeFrom(value);
        }
        literalBuilder_.setMessage(value);
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public Builder clearLiteral() {
      if (literalBuilder_ == null) {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
        }
        literalBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder getLiteralBuilder() {
      return getLiteralFieldBuilder().getBuilder();
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr.LiteralOrBuilder getLiteralOrBuilder() {
      if ((valueCase_ == 1) && (literalBuilder_ != null)) {
        return literalBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 1) {
          return (com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_;
        }
        return com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance();
      }
    }
    /**
     * <code>.peacod_ast.TypeExpr.Literal literal = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.TypeExpr.Literal, com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder, com.sstewartgallus.peacod.ast.TypeExpr.LiteralOrBuilder> 
        getLiteralFieldBuilder() {
      if (literalBuilder_ == null) {
        if (!(valueCase_ == 1)) {
          value_ = com.sstewartgallus.peacod.ast.TypeExpr.Literal.getDefaultInstance();
        }
        literalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sstewartgallus.peacod.ast.TypeExpr.Literal, com.sstewartgallus.peacod.ast.TypeExpr.Literal.Builder, com.sstewartgallus.peacod.ast.TypeExpr.LiteralOrBuilder>(
                (com.sstewartgallus.peacod.ast.TypeExpr.Literal) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 1;
      onChanged();;
      return literalBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.TypeExpr.Variable, com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder, com.sstewartgallus.peacod.ast.TypeExpr.VariableOrBuilder> variableBuilder_;
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public boolean hasVariable() {
      return valueCase_ == 2;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr.Variable getVariable() {
      if (variableBuilder_ == null) {
        if (valueCase_ == 2) {
          return (com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_;
        }
        return com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance();
      } else {
        if (valueCase_ == 2) {
          return variableBuilder_.getMessage();
        }
        return com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance();
      }
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public Builder setVariable(com.sstewartgallus.peacod.ast.TypeExpr.Variable value) {
      if (variableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        variableBuilder_.setMessage(value);
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public Builder setVariable(
        com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder builderForValue) {
      if (variableBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        variableBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public Builder mergeVariable(com.sstewartgallus.peacod.ast.TypeExpr.Variable value) {
      if (variableBuilder_ == null) {
        if (valueCase_ == 2 &&
            value_ != com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance()) {
          value_ = com.sstewartgallus.peacod.ast.TypeExpr.Variable.newBuilder((com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 2) {
          variableBuilder_.mergeFrom(value);
        }
        variableBuilder_.setMessage(value);
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public Builder clearVariable() {
      if (variableBuilder_ == null) {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
        }
        variableBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder getVariableBuilder() {
      return getVariableFieldBuilder().getBuilder();
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    public com.sstewartgallus.peacod.ast.TypeExpr.VariableOrBuilder getVariableOrBuilder() {
      if ((valueCase_ == 2) && (variableBuilder_ != null)) {
        return variableBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 2) {
          return (com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_;
        }
        return com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance();
      }
    }
    /**
     * <code>.peacod_ast.TypeExpr.Variable variable = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sstewartgallus.peacod.ast.TypeExpr.Variable, com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder, com.sstewartgallus.peacod.ast.TypeExpr.VariableOrBuilder> 
        getVariableFieldBuilder() {
      if (variableBuilder_ == null) {
        if (!(valueCase_ == 2)) {
          value_ = com.sstewartgallus.peacod.ast.TypeExpr.Variable.getDefaultInstance();
        }
        variableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sstewartgallus.peacod.ast.TypeExpr.Variable, com.sstewartgallus.peacod.ast.TypeExpr.Variable.Builder, com.sstewartgallus.peacod.ast.TypeExpr.VariableOrBuilder>(
                (com.sstewartgallus.peacod.ast.TypeExpr.Variable) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 2;
      onChanged();;
      return variableBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:peacod_ast.TypeExpr)
  }

  // @@protoc_insertion_point(class_scope:peacod_ast.TypeExpr)
  private static final com.sstewartgallus.peacod.ast.TypeExpr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sstewartgallus.peacod.ast.TypeExpr();
  }

  public static com.sstewartgallus.peacod.ast.TypeExpr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TypeExpr>
      PARSER = new com.google.protobuf.AbstractParser<TypeExpr>() {
    @java.lang.Override
    public TypeExpr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TypeExpr(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TypeExpr> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TypeExpr> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sstewartgallus.peacod.ast.TypeExpr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

